sudo: false

language: scala

scala:
  - 2.13.1
  - 2.12.10

jdk:
  - openjdk11

script: sbt ++$TRAVIS_SCALA_VERSION clean test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete